{% set version = "6.14.0" %}

package:
  name: devpi-server
  version: {{ version }}

source:
  url:
    # - vs _ seems to flip-flop between releases
    - https://pypi.io/packages/source/d/devpi-server/devpi-server-{{ version }}.tar.gz
    - https://pypi.io/packages/source/d/devpi-server/devpi_server-{{ version }}.tar.gz
  sha256: b932e478a7dfee4829223b8c0f989ef631d955aaf8bf42ae4346e26da1745523

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - devpi-export = devpi_server.importexport:export
    - devpi-fsck = devpi_server.fsck:fsck
    - devpi-gen-config = devpi_server.genconfig:genconfig
    - devpi-gen-secret = devpi_server.config:gensecret
    - devpi-import = devpi_server.importexport:import_
    - devpi-init = devpi_server.init:init
    - devpi-passwd = devpi_server.passwd:passwd
    - devpi-server = devpi_server.main:main

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - argon2-cffi
    - attrs >=22.2.0
    - defusedxml
    - devpi-common >3.6.0,<5
    - httpx
    - itsdangerous >=0.24
    - lazy
    - passlib
    - platformdirs
    - pluggy >=0.6.0,<2.0
    - py >=1.4.23
    - pyramid >=2
    - python >=3.7
    - repoze.lru >=0.6
    - ruamel.yaml
    - strictyaml
    - waitress >=1.0.1
    # TODO: handle once added to conda-forge
    # - legacy-cgi

test:
  imports:
    - devpi_server
    - pytest_devpi_server
    - test_devpi_server
  commands:
    - pip check
    - devpi-export --help
    - devpi-fsck --help
    - devpi-gen-config --help
    - devpi-gen-secret --help
    - devpi-import --help
    - devpi-init --help
    - devpi-passwd --help
    - devpi-server --help
  requires:
    - pip
    - pytest

about:
  home: https://devpi.net
  summary: 'devpi-server: reliable private and pypi.org caching server'
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/devpi/devpi

extra:
  recipe-maintainers:
    - bollwyvl
