# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "6.18.0"
  python_check_max: "3.14"

package:
  name: devpi-server
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/devpi-server/devpi_server-${{ version }}.tar.gz
  sha256: 8a38248e9cf4b144f2cacd89ca32a56bbf8d592ae17c2abffb72f403073e9558

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - devpi-export = devpi_server.importexport:export
      - devpi-fsck = devpi_server.fsck:fsck
      - devpi-gen-config = devpi_server.genconfig:genconfig
      - devpi-gen-secret = devpi_server.config:gensecret
      - devpi-import = devpi_server.importexport:import_
      - devpi-init = devpi_server.init:init
      - devpi-passwd = devpi_server.passwd:passwd
      - devpi-server = devpi_server.main:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - argon2-cffi
    - attrs >=22.2.0
    - defusedxml
    - devpi-common >3.6.0,<5
    - httpx <1
    - itsdangerous >=0.24
    - lazy
    - legacy-cgi
    - passlib
    - platformdirs
    - pluggy >=0.6.0,<2.0
    - py >=1.4.23
    - pyramid >=2
    - python >=${{ python_min }}
    - repoze.lru >=0.6
    - ruamel.yaml
    - strenum
    - strictyaml
    - waitress >=1.0.1

tests:
  - python:
      imports:
        - devpi_server
        - pytest_devpi_server
        - test_devpi_server
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*

  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - devpi-export --help
      - devpi-fsck --help
      - devpi-gen-config --help
      - devpi-gen-secret --help
      - devpi-import --help
      - devpi-init --help
      - devpi-passwd --help
      - devpi-server --help

about:
  homepage: https://pypi.org/project/devpi-server
  summary: |-
    devpi-server: reliable private and pypi.org caching server
  license: MIT
  license_file: LICENSE
  repository: https://github.com/devpi/devpi
  documentation: https://docs.devpi.net

extra:
  recipe-maintainers:
    - bollwyvl
